name: Test the example in the readme

on:
  push:
  repository_dispatch:
  workflow_dispatch:

jobs:
  get_architectures:
    runs-on: ubuntu-latest
    outputs:
      list: ${{ steps.arch.outputs.list }}
    steps:
      - uses: Makeshift/get-common-docker-architectures@master
        id: arch
        with:
          images: alpine:3.16.0,centos:centos7.9.2009,debian:stable-20220822-slim

  run_on_each_arch:
    runs-on: ubuntu-latest
    needs: get_architectures
    strategy:
      matrix:
        arch: ${{ fromJson(needs.get_architectures.outputs.list) }}
    steps:
      - run: echo "${{ matrix.arch }}"
